--Los datos de las piezas que han sido suministradas en mayor cantidad

--EJERCICIO 42

-- ROUND --> REDONDEA HACIA ARRIBA

-- TRUNCATE --> QUITA DECIMALES QUE TU LE DIGAS, REDONDEA HACIA ABAJO.

-- FECHAS

-- REPASAR (UPDATES && INSERT) CON SUBCONSULTAS

-- 25 ACTUALIZACION

-- 18 INSERT

-- CREAR TABLA O VISTA

/*      FLOW EXAMEN
1-CONSULTA || SUBCONSULTA
2-CONSULTA || SUBCONSULTA
3-CONSULTA || SUBCONSULTA
4-CONSULTA || SUBCONSULTA
5-CONSULTA || SUBCONSULTA
6-CREAR TABLA O VISTA
7-DELETE
8-UPDATE
9-UPDATE
10-INSERT
*/

/* FECHAS
-CALCULAR FECHAS --> DATEDIFF(FEC_RESTA, FEC_RESTADA); <-- DIAS 
-TIMESTAMPDIFF(YEAR//MONTH//DAY, RESTADA, RESTA -> NOW())
*/

/* BOLETIN04 EJ)22 DUDA */