--//-1. Obtener todos los atributos de todos los proyectos.
--//-2. Obtener todos los atributos de todos los proyectos desarrollados en Londres.
--//-3. Obtener los códigos de las piezas suministradas por el proveedor s2, ordenados.
--//-4. Obtener los códigos de los proveedores del proyecto j1, ordenados.
--//-5. Obtener todas las ocurrencias pieza.color, pieza.ciudad eliminando los pares duplicados.
--//-6. Obtener los códigos de las ventas en los que la cantidad no sea nula.
--//-7. Obtener códigos de los proyectos y ciudades en las que la ciudad del proyecto tenga una 'o' en la segunda letra.
--//-8. Obtener un listado ascendente de los nombres de las piezas con más de 5 letras.
--//-9. Obtener nombres abreviados de proyectos tomando sus primeras 3 letras.
--//-10. Obtener los tres últimos caracteres de los nombres de proveedores por orden alfabético.
--//-11. Hallar cuántas piezas distintas existen.
--//-12. Hallar cuántas piezas distintas existen dando nombre a la columna resultante Número.
--//-13. Obtener el número total de proyectos suministrados por el proveedor sl.
--//-14. Obtener la cantidad total de piezas p1 suministrada por s1.
--//-15. Obtener la cantidad media de piezas suministradas, cantidad máxima y mínima suministrada.
--//-16. Obtener las ventas en las que la cantidad de piezas esté entre 300 y 750 inclusive.
--//-17. Construir una consulta que devuelva codpie y VERDADERO si en la tabla piezas el color de la pieza no es ni azul ni gris.
--//-18. Añade una nueva columna llamada fecha que indique la fecha de adquisición de una pieza por proveedor y proyecto.
--//-19. Modificar la fecha de adquisición de todas las piezas p2 a la fecha actual.
--//-20. Se desea visualizar la fecha con formato del ejemplo ’11-NOV-2002’.
--//-21. Modificar la fecha de adquisición en los que participan los proyectos j1 y j2 a la fecha 12-11-2001 .
--//-22. Construir una lista ordenada de todas las ciudades en las que almenos resida un proveedor o suministrador, una pieza o un proyecto.
--//-23. Obtener todas las posibles combinaciones entre piezas y proveedores.
--//-24. Obtener todos los posibles tríos de código de proveedor, código de pieza y código de proyecto en los que el proveedor, pieza y proyecto estén en la misma ciudad.
--//-25. Obtener los códigos de proveedor, de pieza y de proyecto de aquellos cargamentos en los que proveedor, pieza y proyecto estén en la misma ciudad.
--//-26. Obtener todos los posibles trios de código de proveedor, código de pieza y código de proyecto en los que el proveedor, pieza y proyecto no estén todos en la misma ciudad.
--//-27. Obtener todos los posibles trios de código de proveedor, código de pieza y código de proyecto en los que el proveedor, pieza y proyecto no estén ninguno en la misma ciudad.
--//-28. Obtener los códigos de las piezas suministradas por proveedores de Londres.
--//-29. Obtener los códigos de las piezas suministradas por proveedores de Londres a proyectos en Londres.
--//-30. Obtener todos los pares de nombres de ciudades en las que un proveedor de la primera sirva a un proyecto de la segunda.
--//-31. Obtener códigos de piezas que sean suministradas a un proyecto por un proveedor de la misma ciudad del proyecto.
--//-32. Obtener códigos de proyectos que sean suministrados por un proveedor de una ciudad distinta a la del proyecto. Visualizar el código de proveedor y el del proyecto.
--//-33. Obtener todos los pares de códigos de piezas suministradas por el mismo proveedor.
--//-34. Obtener todos los pares de códigos de piezas suministradas por el mismo proveedor (eliminar pares repetidos).
--//-35. Obtener para cada pieza suministrada a un proyecto, el código de pieza, el código de proyecto y la cantidad total correspondiente.
--//-36. Obtener los códigos de proyectos y los códigos de piezas en los que la cantidad media suministrada a algún proyecto sea superior a 320.
--//-37. Obtener un listado ascendente de los nombres de todos los proveedores que hayan suministrado una cantidad superior a 100 de la pieza p1 . Los nombres deben aparecer en mayúsculas.
--//-38. Obtener los nombres de los proyectos a los que suministra s1.
--//-39. Obtener los colores de las piezas suministradas por s1.
--//-40. Obtener los códigos de las piezas suministradas a cualquier proyecto de Londres.
--//-41. Obtener los códigos de los proveedores con estado menor que el proveedor con código s1.
--//-42. Obtener los códigos de los proyectos que usen la pieza p1 en una cantidad media mayor que la mayor cantidad en la que cualquier pieza sea suministrada al proyecto j1.
--//-43. Obtener códigos de proveedores que suministren a algún proyecto la pieza p1 en una cantidad mayor que la cantidad media en la que se suministra la pieza pI a dicho proyecto.
--//-44. Obtener los códigos de los proyectos que usen al menos una pieza suministrada por s1.
--//-45. Obtener los códigos de los proveedores que suministren al menos una pieza suministrada al menos por un proveedor que suministre al menos una pieza roja.
--//-46. Obtener los codigos de las piezas suministradas a cualquier proyecto de Londres usando EXISTS.
--//-47. Obtener los códigos de los proyectos que usen al menos una pieza suministrada por s1 usando EXISTS.
--//-48. Obtener los códigos de los proyectos que no reciban ninguna pieza roja suministrada por algún proveedor de Londres.
--//-49. Obtener los códigos de los proyectos suministrados únicamente por s1.
--//-50. Obtener los códigos de las piezas suministradas a todos los proyectos en Londres.
--//-51. Obtener los códigos de los proveedores que suministren la misma pieza todos a los proyectos.
--//-52. Obtener los códigos de los proyectos que reciban al menos todas las piezas que suministra s1.
--//-53. Cambiar el color de todas las piezas rojas a naranja.
--//-54. Borrar todos los proyectos para los que no haya cargamentos.
--//-55. Borrar todos los proyectos en Roma y sus correspondientes cargamentos.
--//-56. Insertar un nuevo suministrador s 10 en la tabla S. EI nombre y la ciudad son 'White'y ‘New York' respectivamente. El estado no se conoce todavía.
--//-57. Construir una tabla conteniendo una lista de los códigos de las piezas suministrada.s a proyectos en Londres o suministradas por un suministrador de Londres.
--//-58. Construir una tabla conteniendo una lista de los códigos de los proyectos de Londres o que tengan algún suministrador de Londres.
--//-59. Listar las tablas y secuencias definidas por el usuario ZEUS.